### ISSUE TITLE
想请教一下是如何实现的

### ISSUE THREAD

**Issue by BarryZM** [wuxiaobo/insurance-clause-pdf-format#2]

**Comment by wuxiaobo** [comment]
主要是正则模板发自我的华为手机-------- 原始邮件 --------发件人： BarryZM <notifications@github.com>日期： 2020年11月30日周一 下午4:37收件人： wuxiaobo/insurance-clause-pdf-format <insurance-clause-pdf-format@noreply.github.com>抄送： Subscribed <subscribed@noreply.github.com>主    题： [wuxiaobo/insurance-clause-pdf-format] 想请教一下是如何实现的 (#2)

**Comment by BarryZM** [comment]
非常感谢

**Comment by wuxiaobo** [comment]
基于正则表达式就可以实现
